inherit_gem:
  rubocop-config-timedia:
    - config/base.yml
    - config/rails.yml
    - config/rspec.yml
    - config/factory_bot.yml

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/**/*
    - config/*
    - config/environments/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - public/**/*
    - storage/**/*

Metrics/AbcSize:
  Max: 22
  Include:
    - app/controllers/**/*

Metrics/CyclomaticComplexity:
  Max: 10
  Include:
    - app/controllers/**/*

Metrics/MethodLength:
  Max: 12
  CountAsOne:
    - array
    - hash
    - heredoc
  Include:
    - app/controllers/**/*

Metrics/PerceivedComplexity:
  Max: 10
  Include:
    - app/controllers/**/*

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/NestedGroups:
  Max: 4
  Include:
    - spec/models/*
