openapi: 3.1.0

info:
  title: シンプルなオンラインストレージサービス提供用API
  description: 本APIは、APIとはなにか、どのようにして作成するのかを学ぶためのものである。
  termsOfService: http://localhost:{PORT}/
  version: 0.0.0

paths:
  /signin:
    post:
      summary: ユーザとしてログインする
  /signout:
    delete:
      summary: ユーザとしてログアウトする
  /files:
    get:
      summary: アップロードされたファイル一覧を返す
    post:
      summary: 新しいファイルをアップロードする
  /files/{fileId}:
    get:
      summary: ファイル名やその説明文、あるいはファイル自身などファイルの情報を返す
    patch:
      summary: ファイルの情報を更新する
    delete:
      summary: アップロードされているファイルを削除する
    parameters:
      - name: fileId
  /user:
    get:
      summary: 現在自分がログインしているユーザの情報を返す
    post:
      summary: 新しいユーザを作成する
    patch:
      summary: 現在自分がログインしているユーザの情報を更新する
    delete:
      summary: 現在自分がログインしているユーザの情報を削除する
